# Generated by Django 4.1.3 on 2023-06-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaestudi',
            old_name='question_text',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='plaestudi',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='plaestudi',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
